create table person
(
    id        int generated by default as identity primary key,
    name      varchar(32)                                      not null,
    lastname  varchar(32)                                      not null,
    inn       varchar(10) check ( inn ~ '^[0-9]{10}$' ) unique not null,
    birthdate date
);

drop table person;

insert into person (name, lastname, inn, birthdate)
values ('Oleksii', 'Bashkirov', '3332221110', '1989-08-25');

select *
from person;