create table person
(
    id        int generated by default as identity primary key,
    name      varchar(32)                                      not null,
    lastname  varchar(32)                                      not null,
    inn       varchar(10) check ( inn ~ '^[0-9]{10}$' ) unique not null,
    birthdate date
);

insert into person (name, lastname, inn, birthdate)
values ('Oleksii', 'Bashkirov', '3332221110', '1989-08-25'),
       ('Ivan', 'Petrov', '3231212456', '2001-02-15'),
       ('Sveta', 'Kozakova', '3202504585', '1995-09-29'),
       ('Olga', 'Vasilenko', '3012546545', '1975-04-11'),
       ('Igor', 'Smirenko', '2904561232', '1960-05-09');



select *
from person;